name: Validate

on: [push, pull_request]

jobs:
  build:
    name: Build, lint, and test on Node LTS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Cache build outputs
        uses: actions/cache@v4
        with:
          path: |
            dist
            .eslintcache
          key: ${{ runner.os }}-build-${{ hashFiles('src/**/*', 'tsconfig.json', 'eslint.config.js') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Cache test results
        uses: actions/cache@v4
        with:
          path: |
            .jest
            node_modules/.cache
          key: ${{ runner.os }}-tests-${{ hashFiles('src/**/*.test.*', 'src/**/*.spec.*', 'jest.config.ts', 'vitest.config.ts') }}
          restore-keys: |
            ${{ runner.os }}-tests-

      - name: Install dependencies
        run: npm ci

      - name: Install example dependencies
        run: npm ci
        working-directory: ./examples

      - name: Lint
        run: npm run lint -- --cache

      - name: Type check
        run: npm run typecheck

      - name: Test all suites in parallel
        run: npm-run-all -p test:jest test:swc test:vi test:browser test:examples

      - name: Build
        run: npm run build
